[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ragkit-baseline"
version = "0.0.1"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["ingest","index","retriever","answer","orchestrator","scripts"]
