chunk_size_tokens: 300
chunk_overlap_tokens: 50
top_k_dense: 12
top_k_bm25: 6
dense_backend: auto                # auto|sbert|lsa
dense_model_name: paraphrase-multilingual-MiniLM-L12-v2
dense_device: auto                 # auto|cpu|cuda
dense_max_batch: 64
dense_normalize: true              # L2-нормировка эмбеддингов
rerank_mode: auto                  # auto|ce|heuristic
ce_model_name: cross-encoder/ms-marco-MiniLM-L-6-v2
ce_max_batch: 32
rerank_in: 24
rerank_out: 2
answer_max_pages: 2
timeout_per_q_seconds: 90
orchestrator_concurrency: 8
rerank_batch_size: 4
cot_enabled_types: ["number", "compare", "aggregate"]
number_tolerance_pct: 0.5
boolean_tokens: ["да","нет","иә","жоқ","yes","no"]
language_mode: "auto"
hybrid_alpha: 0.7
enable_caching: true
retrieval_cache_size: 512
rerank_cache_size: 1024
enable_metrics_logging: true
